---
title: "Meh"
date: 2022-03-26
---
title: Meh
author: David
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 this site is a test. please ignore. 

# social links
twitter_username: iamdavidbill # DO NOT include the @ character, or else the build will fail!
github_username:  davidsbill # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
